#!/usr/bin/env python3
"""Search heuristics and domain data for the JackIn media search engine.

Isolated here so the data stays in one place and can be edited without
touching the search logic. Tuning thresholds live here too.
"""

STOP_WORDS = {"the", "a", "an", "in", "on", "of", "for", "to", "and", "is", "it", "at", "by", "or", "no", "be"}

MIN_RELEVANCE = 0.4

# Candidate pool & option tuning
MIN_CANDIDATES = 6
MAX_OPTIONS = 6
MIN_SEEDERS = 1
PREFERRED_SEEDERS = 5

# Quality tiers in descending preference order
QUALITY_TIERS = ["REMUX", "4K", "1080P", "720P", "WEBRIP", "OTHER"]

# Size sanity (GB) per tier: [min, max]
SIZE_TIERS = {
    "REMUX": (15.0, 120.0),
    "4K": (5.0, 60.0),
    "1080P": (1.0, 30.0),
    "720P": (0.5, 10.0),
    "WEBRIP": (0.5, 10.0),
    "OTHER": (0.3, 60.0),
}

# Composite candidate score weights
SCORE_WEIGHTS = {
    "seeders": 0.40,
    "relevance": 0.35,
    "quality": 0.15,
    "size_sanity": 0.10,
}

GENERIC_BLOCKLIST = {
    "action", "comedy", "horror", "drama", "sci-fi", "thriller", "romance",
    "documentary", "animation", "adventure", "fantasy", "mystery", "crime",
    "filme", "serie", "guerra", "amor", "aventura", "terror", "comedia",
    "animacao", "documentario", "lancamentos", "netflix", "hbo", "disney",
    "marvel", "dc", "pixar", "brasil", "download", "dublado", "legendado",
    "best movies", "top films", "new releases", "dc comics",
    "filmes dublados", "series 2024", "2024 filmes",
}

COMPOUND_TRANSLATIONS = {
    "parte dois": "Part Two",
    "parte 2": "Part Two",
    "parte ii": "Part Two",
    "parte um": "Part One",
    "parte 1": "Part One",
    "parte i": "Part One",
    "parte tres": "Part Three",
    "parte 3": "Part Three",
    "parte iii": "Part Three",
    "capitulo final": "Final Chapter",
    "a ascensao": "The Rise",
    "o despertar": "The Awakening",
    "a vinganca": "The Revenge",
    "o inicio": "The Beginning",
    "o fim": "The End",
    "a saga": "",
    "saga": "",
    "novo imperio": "New Empire",
    # ── Franchise subtitle parts (compound phrases that break word-level translation) ──
    "acerto de contas": "Dead Reckoning",
    "a cantiga dos passaros": "Ballad of Songbirds",
    "a cantiga dos pássaros": "Ballad of Songbirds",
    "o reino perdido": "The Lost Kingdom",
    "o despertar das feras": "Rise of the Beasts",
    "a reliquia do destino": "Dial of Destiny",
    "os aneis de poder": "Rings of Power",
    "estrada da furia": "Fury Road",
    "em busca da perfeicao": "Whiplash",
    "atraves do aranhaverso": "Across the Spider-Verse",
    "o caminho da agua": "The Way of Water",
    "sem volta para casa": "No Way Home",
    "sem limites": "No Limits",
    "além do aranhaverso": "Beyond the Spider-Verse",
    "a esperanca o final": "Mockingjay Part 2",
    "o final": "The Final",
    "parte final": "Final Chapter",
    "era de ultron": "Age of Ultron",
    "guerra infinita": "Infinity War",
    "guerra civil": "Civil War",
    "a sociedade do anel": "The Fellowship of the Ring",
    "as duas torres": "The Two Towers",
    "o retorno do rei": "The Return of the King",
    "a guerra dos rohirrim": "The War of the Rohirrim",
    "trilogia o senhor dos aneis": "The Lord of the Rings Trilogy",
    "trilogia estendida o senhor dos aneis": "The Lord of the Rings Trilogy",
    "o hobbit uma jornada inesperada": "The Hobbit: An Unexpected Journey",
    "o hobbit a desolacao de smaug": "The Hobbit: The Desolation of Smaug",
    "o hobbit a batalha dos cinco exercitos": "The Hobbit: The Battle of the Five Armies",
    "velozes e furiosos desafio em toquio": "Tokyo Drift",
    "velozes e furiosos 5 operacao rio": "Fast Five",
    "missao impossivel acerto de contas": "Mission: Impossible - Dead Reckoning",
    "missao impossivel efeito fallou": "Mission: Impossible - Fallout",
    "missao impossivel nacao secreta": "Mission: Impossible - Rogue Nation",
    "missao impossivel protocolo fantasma": "Mission: Impossible - Ghost Protocol",
    "harry potter e a pedra filosofal": "Harry Potter and the Philosopher's Stone",
    "harry potter e a camara secreta": "Harry Potter and the Chamber of Secrets",
    "harry potter e o prisioneiro de azkaban": "Harry Potter and the Prisoner of Azkaban",
    "harry potter e o calice de fogo": "Harry Potter and the Goblet of Fire",
    "harry potter e a ordem da fenix": "Harry Potter and the Order of the Phoenix",
    "harry potter e o enigma do principe": "Harry Potter and the Half-Blood Prince",
    "harry potter e as reliquias da morte": "Harry Potter and the Deathly Hallows",
    "o poderoso chefao parte ii": "The Godfather Part II",
    "o poderoso chefao parte iii": "The Godfather Part III",
    "de volta para o futuro parte ii": "Back to the Future Part II",
    "de volta para o futuro parte iii": "Back to the Future Part III",
    "jurassic world dominio": "Jurassic World Dominion",
    "jurassic world reino ameacado": "Jurassic World: Fallen Kingdom",
    "pantera negra wakanda forever": "Black Panther: Wakanda Forever",
    "homem aranha sem volta para casa": "Spider-Man: No Way Home",
    "homem aranha longe de casa": "Spider-Man: Far From Home",
    "homem aranha de volta ao lar": "Spider-Man: Homecoming",
    "doutor estranho no multiverso da loucura": "Doctor Strange in the Multiverse of Madness",
    "guerreiros do futuro": "Future Warriors",
    "os vingadores the avengers": "The Avengers",
    "guerra mundial z": "World War Z",
    "o massacre da serra eletrica": "The Texas Chain Saw Massacre",
    "a freira": "The Nun",
    "invocacao do mal": "The Conjuring",
    "annabelle": "Annabelle",
    "it a coisa": "It",
    "toy story 4": "Toy Story 4",
    "como treinar o seu dragao 3": "How to Train Your Dragon 3",
    "piratas do caribe a maldicao do perola negra": "Pirates of the Caribbean The Curse of the Black Pearl",
    "piratas do caribe o bau da morte": "Pirates of the Caribbean Dead Mans Chest",
    "piratas do caribe no fim do mundo": "Pirates of the Caribbean At Worlds End",
    "piratas do caribe navegando em aguas misteriosas": "Pirates of the Caribbean On Stranger Tides",
    "piratas do caribe a vinganca de salazar": "Pirates of the Caribbean Dead Men Tell No Tales",
    "a maldicao do perola negra": "The Curse of the Black Pearl",
    "o bau da morte": "Dead Mans Chest",
    "no fim do mundo": "At Worlds End",
    "navegando em aguas misteriosas": "On Stranger Tides",
    "a vinganca de salazar": "Dead Men Tell No Tales",
}

# Mapeamento especial para buscas populares e termos curtos
SPECIAL_MOVIE_MAP = {
    "up": "Up (2009)",
    "up altas aventuras": "Up (2009)",
    "up - altas aventuras": "Up (2009)",
    "altas aventuras": "Up (2009)",
    "treasure planet": [
        {
            "title": "O Planeta do Tesouro",
            "originalTitle": "Treasure Planet",
            "year": "2002",
            "overview": "Um mapa secreto inspira uma emocionante caça ao tesouro pelo universo quando o jovem Jim Hawkins parte em um galão espacial em busca do seu destino. A bordo de uma nave lendária, ele descobre o verdadeiro valor da amizade e da coragem.",
            "posterUrl": "https://upload.wikimedia.org/wikipedia/pt/3/3f/Treasure_Planet_%28Disney%29.jpg",
            "genre": "Animação / Ficção Científica",
            "rating": "7.3/10"
        }
    ],
    "planeta do tesouro": "treasure planet",
    "o planeta do tesouro": "treasure planet",
    "planeta": "treasure planet",
    "tesouro": "treasure planet",
}

# Dicionário de tradução comum para termos em português
TRANSLATIONS = {
    "planeta do tesouro": "treasure planet",
    "o planeta do tesouro": "treasure planet",
    "divertida mente": "inside out",
    "detona ralph": "wreck-it ralph",
    "os incriveis": "the incredibles",
    "como treinar o seu dragao": "how to train your dragon",
    "enrolados": "tangled",
    "valente": "brave",
    "monstros sa": "monsters inc",
    "procurando nemo": "finding nemo",
    "procurando dory": "finding dory",
    "vida de inseto": "a bugs life",
    "a pequena sereia": "the little mermaid",
    "a bela e a fera": "beauty and the beast",
    "o rei leao": "the lion king",
    "irmão urso": "brother bear",
    "irmao urso": "brother bear",
    "red crescer e uma fera": "turning red",
    "elementos": "elemental",
    "super mario": "super mario",
    "gato de botas": "puss in boots",
    "meu malvado favorito": "despicable me",
    "minions": "minions",
    "moana": "moana",
    "zootopia": "zootopia",
    "vingadores": "avengers",
    "homem aranha": "spider-man",
    "homem de ferro": "iron man",
    "capitao america": "captain america",
    "batman": "batman",
    "superman": "superman",
    "coringa": "joker",
    "toy story": "toy story",
    "carros": "cars",
    "rei leao": "lion king",
    "madagascar": "madagascar",
    "shrek": "shrek",
    "gladiador": "gladiator",
    "pantera negra": "black panther",
    "doutor estranho": "doctor strange",
    # ── Compound title patterns (longest first — CRITICAL for _pt_to_en ordering) ──
    "duna parte dois": "Dune Part Two",
    "duna parte 2": "Dune Part Two",
    "duna parte um": "Dune Part One",
    "duna parte 1": "Dune Part One",
    "senhor dos aneis a sociedade do anel": "The Lord of the Rings The Fellowship of the Ring",
    "senhor dos aneis as duas torres": "The Lord of the Rings The Two Towers",
    "senhor dos aneis o retorno do rei": "The Lord of the Rings The Return of the King",
    "star wars a ascensao skywalker": "Star Wars The Rise of Skywalker",
    "star wars o despertar da forca": "Star Wars The Force Awakens",
    "star wars os ultimos jedi": "Star Wars The Last Jedi",
    "star wars uma nova esperanca": "Star Wars A New Hope",
    "star wars o imperio contra ataca": "Star Wars The Empire Strikes Back",
    "star wars o retorno de jedi": "Star Wars Return of the Jedi",
    "star wars a ameaca fantasma": "Star Wars The Phantom Menace",
    "star wars ataque dos clones": "Star Wars Attack of the Clones",
    "star wars a vinganca dos sith": "Star Wars Revenge of the Sith",
    "star wars rogue one": "Rogue One A Star Wars Story",
    "a sociedade do anel": "the fellowship of the ring",
    "as duas torres": "the two towers",
    "o retorno do rei": "the return of the king",
    "a guerra dos rohirrim": "the war of the rohirrim",
    "trilogia o senhor dos aneis": "the lord of the rings trilogy",
    "trilogia estendida o senhor dos aneis": "the lord of the rings trilogy",
    "jogos vorazes em chamas": "The Hunger Games Catching Fire",
    "jogos vorazes a esperanca": "The Hunger Games Mockingjay",
    "jogos vorazes": "The Hunger Games",
    "a culpa e das estrelas": "The Fault in Our Stars",
    "oq fazer com um marido no divorcio": "What to Do With a Husband in Divorce",
    "guerra infinita": "infinity war",
    "ultimato": "endgame",
    "guerra civil": "civil war",
    "era de ultron": "age of ultron",
    "liga da justica": "justice league",
    "esquadrao suicida": "suicide squad",
    "mulher maravilha": "wonder woman",
    "velozes e furiosos": "fast and furious",
    "jurassic world": "jurassic world",
    "mundo jurassico": "jurassic world",
    "star wars": "star wars",
    "guerra nas estrelas": "star wars",
    "senhor dos aneis": "the lord of the rings",
    "o senhor dos aneis": "the lord of the rings",
    "harry potter": "harry potter",
    "transformers": "transformers",
    "missao impossivel": "mission impossible",
    "piratas do caribe": "pirates of the caribbean",
    "matrix": "matrix",
    "interestelar": "interstellar",
    "a origem": "inception",
    "clube da luta": "fight club",
    "o poderoso chefao": "the godfather",
    "forrest gump": "forrest gump",
    "de volta pro futuro": "back to the future",
    "exterminador do futuro": "terminator",
    # ── Compound franchise titles missing from earlier mapping ──
    "jogos vorazes a cantiga dos passaros": "The Hunger Games The Ballad of Songbirds",
    "missao impossivel acerto de contas": "Mission Impossible Dead Reckoning",
    "o senhor dos aneis os aneis de poder": "The Lord of the Rings The Rings of Power",
    "fast and furious 10": "Fast X",
    "o exterminador do futuro 2": "Terminator 2",
    "exterminador do futuro 2": "Terminator 2",
    "caça fantasmas": "Ghostbusters",
    "os cacafantasmas": "Ghostbusters",
    "caca fantasmas": "Ghostbusters",
    # ── Sequels / number-suffixed titles — QA found these missing ──
    "panico 4": "Scream 4",
    "panico 5": "Scream 5",
    "panico 6": "Scream 6",
    "mib 2": "Men in Black 2",
    "mib 3": "Men in Black 3",
    "os bad boys 2": "Bad Boys 2",
    "bad boys 2": "Bad Boys 2",
    "missao impossivel 2": "Mission Impossible 2",
    "missao impossivel 3": "Mission Impossible 3",
    "duro de matar 3": "Die Hard 3",
    "sobrenatural 2": "Insidious 2",
    "sobrenatural 3": "Insidious 3",
    "aladdin 2": "Aladdin 2",
    "homem-formiga 3": "Ant-Man and the Wasp Quantumania",
    "aquaman 2 o reino perdido": "Aquaman and the Lost Kingdom",
    "um lugar silencioso 2": "A Quiet Place Part II",
    # ── Ghibli / anime PT titles missing from mapping ──
    "castelo no ceu": "Castle in the Sky",
    "meus vizinhos os yamadas": "My Neighbors the Yamadas",
    "o vento levanta": "The Wind Rises",
    "memorias de ontem": "Only Yesterday",
    "o reino dos gatos": "The Cat Returns",
    "o servico de entregas da kiki": "Kiki's Delivery Service",
    "squid game": "Squid Game",
    "round 6": "Squid Game",
    "duna": "dune",
    "deadpool": "deadpool",
    "wolverine": "wolverine",
    "logan": "logan",
    "avatar": "avatar",
    # ── Typos comuns (mapeiam para o termo correto) ──
    "sennor dos anelis": "the lord of the rings",
    "sennor dos aneis": "the lord of the rings",
    "sennor": "senhor",
    "anelis": "aneis",
    "guera nas estrelas": "star wars",
    "guerra nas strelas": "star wars",
    "harry poter": "harry potter",
    "miranha": "spider-man",
    "homem aramha": "spider-man",
    "apider man": "spider-man",
    "batima": "batman",
}

# Idiomas indesejados (blocklist por token no nome do torrent)
BLACKLIST_LANGS = {
    "ITA", "ITALIAN", "ITALIANO", "GER", "GERMAN", "DEUTSCH",
    "FRE", "FRENCH", "FRANCAIS", "SPA", "SPANISH", "ESPANOL",
    "CASTELLANO", "RUS", "RUSSIAN", "HINDI", "TAMIL", "TELUGU",
    "TUR", "TURKISH", "TURG", "HIN", "KOR", "KOREAN", "JPN", "JAPANESE",
    "ARB", "ARABIC", "THA", "THAI", "VIE", "VIETNAMESE", "IND", "INDONESIAN",
    "POL", "POLISH", "DAN", "DANISH", "SWE", "SWEDISH", "NOR", "NORWEGIAN",
    "FIN", "FINNISH", "CZE", "CZECH", "NLD", "DUTCH", "HUN", "HUNGARIAN",
}

# Markers in a torrent name that CONFIRM Portuguese-Brazilian audio (not just
# a generic "DUAL" which could be EN+ES/EN+FR). Only these are labelled PT-BR.
PT_AUDIO_MARKERS = (
    "DUBLADO", "DUBLADOS", "DUBLADO-PT", "DUB-PT", "DUB POR",
    "PT-BR", "PTBR", "PORTUGUES", "PORTUGUESE", "PORTUGUÊS", "BRAZILIAN",
)

# Reverse (English -> Portuguese) translation map for query expansion
REVERSE_TRANSLATIONS = {
    "treasure planet": "planeta do tesouro",
    "inside out": "divertida mente",
    "the incredibles": "os incriveis",
    "how to train your dragon": "como treinar o seu dragao",
    "tangled": "enrolados",
    "monsters inc": "monstros sa",
    "finding nemo": "procurando nemo",
    "finding dory": "procurando dory",
    "the little mermaid": "a pequena sereia",
    "the lion king": "o rei leao",
    "turning red": "red crescer e uma fera",
    "puss in boots": "gato de botas",
    "despicable me": "meu malvado favorito",
    "spider-man": "homem aranha",
    "iron man": "homem de ferro",
    "captain america": "capitao america",
    "avengers": "vingadores",
    "fast and furious": "velozes e furiosos",
    "lord of the rings": "senhor dos aneis",
    "mission impossible": "missao impossivel",
    "pirates of the caribbean": "piratas do caribe",
    "back to the future": "de volta pro futuro",
    "terminator": "exterminador do futuro",
    "dune": "duna",
    "dune part two": "duna parte 2",
    "dune part one": "duna parte 1",
    "the lord of the rings the fellowship of the ring": "senhor dos aneis a sociedade do anel",
    "the lord of the rings the two towers": "senhor dos aneis as duas torres",
    "the lord of the rings the return of the king": "senhor dos aneis o retorno do rei",
    "the hobbit": "o hobbit",
    "the hunger games": "jogos vorazes",
    "star wars the force awakens": "star wars o despertar da forca",
    "star wars the last jedi": "star wars os ultimos jedi",
    "star wars the rise of skywalker": "star wars a ascensao skywalker",
    "spider-man no way home": "homem aranha sem volta para casa",
    "spider-man far from home": "homem aranha longe de casa",
    "spider-man homecoming": "homem aranha de volta ao lar",
}

# Patterns that indicate the result is junk content (music, ebooks, pron, etc.)
JUNK_PATTERNS = [
    r"\b(album|ost|soundtrack|flac|mp3|opus|320kbps|bitrate)\b",
    r"\.(epub|pdf|mobi|djvu|cbr|cbz|azw3|txt)\b",
    r"\b(anal|bareback|brazzers|bangbros|pornhub|xnxx|xvideos|sex tape|tushy|onlyfans|milf|xxx|cum|cuckold|hentai)\b",
    r"\b(sample|dummy|readme|podcast|audiobook)\b",
    r"\b(audio\s*book|audiobooks)\b",
    r"\b(unabridged|abridged)\b",
    r"\b(read|narrated)[\s.\-_]+by\b|\b(narrator|audible|audiobook)\b",
]
